spring.application.name=gestion-solicitudes

# Conexion con la BD MySQL
spring.datasource.url=jdbc:postgresql://ep-fancy-frost-amndsdnh.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_VEq2Ajgh8nZS
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.query.substitutions=true

# Contexto API
server.servlet.context-path=/api

# JWT
jwt.secret=miClaveSecretaUniQuindio2026Gestion
jwt.expiration-ms=86400000

# Configuracion de Asistente IA
ia.habilitada=true
ia.api.url=https://api.groq.com/openai/v1/chat/completions
ia.api.key=
ia.api.model=llama-3.3-70b-versatile