spring.application.name=gestion-solicitudes

# Conexion con la BD MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/solicitud_academica
spring.datasource.username=root
spring.datasource.password=Poseidon
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Conexto API
server.servlet.context-path=/api

# JWT
jwt.secret=miClaveSecretaUniQuindio2026Gestion
ywt.expiration-ms=86400000