spring.application.name=gestion-solicitudes

# Conexión con la BD MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/solicitud_academica
spring.datasource.username=root
spring.datasource.password=Poseidon

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
